import * as React from "react";
import { PixiBaseSpriteProps, ForwardedRefResponse } from "../../types/BaseProps";
import { Effects } from "../../types/Effects";
import { Animations } from "../../types";
export interface PixiSvgPathSpriteProps extends PixiBaseSpriteProps {
    uniqueId: string;
    path: string;
    startAt: number;
    endAt: number;
    transformation: {
        x: number;
        y: number;
        width: number;
        height: number;
        anchor: number;
        rotation?: number;
        alpha?: number;
        scale?: number | [number, number];
        tint?: number;
        blendMode?: number;
        animation?: Animations;
        hexColor?: string;
        fill?: string;
        fontWeight?: string;
        fontStyle?: string;
        stroke?: string;
        strokeWidth?: number;
        blurRadius?: number;
        colorCorrection?: {
            enabled?: boolean;
            temperature?: number;
            hue?: number;
            contrast?: number;
            saturation?: number;
            exposure?: number;
            reset?: boolean;
            sharpness?: number;
            value?: number;
            levels?: number;
            luminance?: number;
            enhance?: number;
            blurRadius?: number;
            red?: number;
            green?: number;
            blue?: number;
            alpha?: number;
            scaleInput?: number;
            vignette?: number;
            noise?: number;
        };
        effect?: Effects;
    };
    pointerdown?: () => void;
    pointerup?: () => void;
    mousedown?: () => void;
    mouseup?: () => void;
    pointerover?: () => void;
    mouseover?: () => void;
    mouseout?: () => void;
    applyTransformer?: boolean;
    onAnchorTransformationEnd?: (endData: any) => void;
}
declare const PixiSvgPathSprite: React.ForwardRefExoticComponent<PixiSvgPathSpriteProps & React.RefAttributes<ForwardedRefResponse | null>>;
export default PixiSvgPathSprite;
