import * as React from "react";
import { PixiBaseSpriteProps, ForwardedRefResponse } from "../../types/BaseProps";
import { Effects } from "../../types/Effects";
import { Animations } from "../../types";
export interface PixiTextSpriteProps extends PixiBaseSpriteProps {
    text: string;
    startAt: number;
    endAt: number;
    disabled?: boolean;
    transformation: {
        x: number;
        y: number;
        width: number;
        height: number;
        anchor: number;
        rotation?: number;
        alpha?: number;
        scale?: number | [number, number];
        tint?: number;
        blendMode?: number;
        animation?: Animations;
        fontWeight?: string;
        fontSize?: number;
        fontFamily?: string;
        fontStyle?: string;
        fontColor?: string;
        fontVariant?: string;
        lineHeight?: number;
        letterSpacing?: number;
        textDecoration?: string;
        wordWrap?: boolean;
        wordWrapWidth?: number;
        leading?: number;
        padding?: number;
        border?: string;
        dropShadow?: boolean;
        dropShadowColor?: string | number;
        shadowOffsetX?: number;
        shadowOffsetY?: number;
        dropShadowBlur?: number;
        blurEnabled?: boolean;
        blurRadius?: number;
        fill: string | number;
        stroke?: string | number;
        strokeThickness?: number;
        zIndex?: number;
        align?: string;
        textBaseline?: string;
        trim?: boolean;
        colorCorrection?: {
            enabled?: boolean;
            temperature?: number;
            hue?: number;
            contrast?: number;
            saturation?: number;
            exposure?: number;
            reset?: boolean;
            sharpness?: number;
            value?: number;
            levels?: number;
            luminance?: number;
            enhance?: number;
            blurRadius?: number;
            red?: number;
            green?: number;
            blue?: number;
            alpha?: number;
            scaleInput?: number;
        };
        effect?: Effects;
    };
    pointerdown?: () => void;
    pointerup?: () => void;
    mousedown?: () => void;
    mouseup?: () => void;
    pointerover?: () => void;
    mouseover?: () => void;
    mouseout?: () => void;
    applyTransformer?: boolean;
    onTextUpdate?: (data: any) => void;
    onAnchorTransformationEnd?: (endData: any) => void;
    onDobuleClick?: () => void;
}
declare const PixiTextSprite: React.ForwardRefExoticComponent<PixiTextSpriteProps & React.RefAttributes<ForwardedRefResponse | null>>;
export default PixiTextSprite;
